/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author tbash
 */
public class AdminStaff_Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminStaff_Dashboard.class.getName());

    /**
     * Creates new form AdminStaff_dashbord
     */
    public AdminStaff_Dashboard() {
        initComponents();
        
//        ImageIcon APUIcon = new ImageIcon("src/Images/AsiaPacificUniversityOfTechnology&Innovation.svg.png");
//        java.awt.Image img = APUIcon.getImage();
//        java.awt.Image scaledImg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
//        ImageIcon scaledIcon = new ImageIcon(scaledImg);
//        ImageIconAD.setIcon(scaledIcon);
        
        ImageIcon userIcone = new ImageIcon("src/Images/user.png");
        java.awt.Image scaledImage = userIcone.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon resizedIcon = new javax.swing.ImageIcon(scaledImage);
        userManagementBT.setIcon(resizedIcon);  
        
        ImageIcon assetIcon = new ImageIcon("src/Images/solid.png");
        java.awt.Image scaledImage2 = assetIcon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon resizedIcon2 = new javax.swing.ImageIcon(scaledImage2);
        assetManagementBT.setIcon(resizedIcon2); 
        
        ImageIcon systemConfigIcone = new ImageIcon("src/Images/business.png");
        java.awt.Image scaledImage3 = systemConfigIcone.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon resizedIcon3 = new javax.swing.ImageIcon(scaledImage3);
        systemConfigBT.setIcon(resizedIcon3); 
        
        
        ImageIcon assignIcon = new ImageIcon("src/Images/selection.png");
        java.awt.Image scaledImage4 = assignIcon.getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon resizedIcon4 = new javax.swing.ImageIcon(scaledImage4);
        assignManagersBT.setIcon(resizedIcon4); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        systemConfigBT = new javax.swing.JButton();
        assetManagementBT = new javax.swing.JButton();
        assignManagersBT = new javax.swing.JButton();
        userManagementBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(240, 244, 248));

        systemConfigBT.setBackground(new java.awt.Color(0, 113, 149));
        systemConfigBT.setForeground(new java.awt.Color(255, 255, 255));
        systemConfigBT.setText("System Configuration");
        systemConfigBT.addActionListener(this::systemConfigBTActionPerformed);

        assetManagementBT.setBackground(new java.awt.Color(0, 113, 149));
        assetManagementBT.setForeground(new java.awt.Color(255, 255, 255));
        assetManagementBT.setText("Asset Management");
        assetManagementBT.addActionListener(this::assetManagementBTActionPerformed);

        assignManagersBT.setBackground(new java.awt.Color(0, 113, 149));
        assignManagersBT.setForeground(new java.awt.Color(255, 255, 255));
        assignManagersBT.setText("Assign Managers");
        assignManagersBT.addActionListener(this::assignManagersBTActionPerformed);

        userManagementBT.setBackground(new java.awt.Color(0, 113, 149));
        userManagementBT.setForeground(new java.awt.Color(255, 255, 255));
        userManagementBT.setText("User Management");
        userManagementBT.addActionListener(this::userManagementBTActionPerformed);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Admin Dashboard");

        jPanel2.setBackground(new java.awt.Color(35, 77, 113));

        logoutBT.setBackground(new java.awt.Color(25, 130, 255));
        logoutBT.setForeground(new java.awt.Color(255, 255, 255));
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assignManagersBT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userManagementBT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetManagementBT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemConfigBT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userManagementBT)
                    .addComponent(assetManagementBT))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignManagersBT)
                    .addComponent(systemConfigBT))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void userManagementBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementBTActionPerformed
        // TODO add your handling code here:
        new User_Management().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userManagementBTActionPerformed

    private void assetManagementBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetManagementBTActionPerformed
        // TODO add your handling code here:
        new Asset_Management().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assetManagementBTActionPerformed

    private void assignManagersBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignManagersBTActionPerformed
        // TODO add your handling code here:
        new Assign_Managers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignManagersBTActionPerformed

    private void systemConfigBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemConfigBTActionPerformed
        // TODO add your handling code here:
        new System_Configuration_Rate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_systemConfigBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminStaff_Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assetManagementBT;
    private javax.swing.JButton assignManagersBT;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton systemConfigBT;
    private javax.swing.JButton userManagementBT;
    // End of variables declaration//GEN-END:variables
}
