/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import models.AdminStaff;
import hospitalmanagementsystem.model.HospitalAsset;
import hospitalmanagementsystem.model.TableManager;

/**
 *
 * @author tbash
 */
public class Asset_Management extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Asset_Management.class.getName());

    /**
     * Creates new form Asset_Management
     */
    public Asset_Management() {
        initComponents();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        assetIdTF = new javax.swing.JTextField();
        assetNameTF = new javax.swing.JTextField();
        assetTypeCB = new javax.swing.JComboBox<>();
        locationCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        assetsTB = new javax.swing.JTable();
        statusCB = new javax.swing.JComboBox<>();
        addAssetBT = new javax.swing.JButton();
        deleteAssetBT = new javax.swing.JButton();
        updateAssetBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        backBT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" Asset ID");

        jLabel2.setText("Asset Name");

        jLabel3.setText(" Asset Type");

        jLabel4.setText("Location");

        jLabel5.setText("Status");

        assetTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room", "Ward", "Laboratory", "Radiology", "Operating Theater", "Clinic" }));

        locationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floor G", "Floor 1", "Floor 2", "Floor 3", "Floor 4" }));

        assetsTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assetsTB.getTableHeader().setReorderingAllowed(false);
        assetsTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assetsTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(assetsTB);

        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Under Maintenance", "Out of Order", "Discarded", "Occupied" }));

        addAssetBT.setText("Add Asset");
        addAssetBT.addActionListener(this::addAssetBTActionPerformed);

        deleteAssetBT.setText("Delete Asset");
        deleteAssetBT.addActionListener(this::deleteAssetBTActionPerformed);

        updateAssetBT.setText("Update Asset");
        updateAssetBT.addActionListener(this::updateAssetBTActionPerformed);

        logoutBT.setBackground(new java.awt.Color(0, 51, 153));
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        backBT.setText("Back");
        backBT.addActionListener(this::backBTActionPerformed);

        jLabel8.setText("ASSET MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(locationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(assetNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(assetTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addAssetBT)
                        .addGap(71, 71, 71)
                        .addComponent(updateAssetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteAssetBT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBT)
                    .addComponent(backBT))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assetIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assetNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assetTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAssetBT)
                    .addComponent(updateAssetBT)
                    .addComponent(addAssetBT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new AdminStaff_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void addAssetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAssetBTActionPerformed
        // TODO add your handling code here:
        
        if (assetIdTF.getText().trim().isEmpty() || assetNameTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all text fields!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = assetIdTF.getText().trim();
        String name = assetNameTF.getText().trim();
        String type = assetTypeCB.getSelectedItem().toString(); 
        String location = locationCB.getSelectedItem().toString(); 
        String status = statusCB.getSelectedItem().toString(); 

        AdminStaff admin = new AdminStaff();

        if (admin.checkAssets(id)) {
            JOptionPane.showMessageDialog(this, "Asset ID already exists! Please use a different ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        HospitalAsset newAsset = new HospitalAsset(id, name, type, location, status);

        boolean success = admin.manageHospitalAssets(newAsset);

        if (success) {
            JOptionPane.showMessageDialog(this, "Asset Added Successfully!");


        } else {
            JOptionPane.showMessageDialog(this, "Failed to add asset.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

        assetIdTF.setText("");
        assetNameTF.setText("");
        assetTypeCB.setSelectedIndex(0);
        locationCB.setSelectedIndex(0);
        statusCB.setSelectedIndex(0);
        refreshTable(); 

    }//GEN-LAST:event_addAssetBTActionPerformed

    private void updateAssetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAssetBTActionPerformed
        // TODO add your handling code here:
        int selectedRow = assetsTB.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an asset from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (assetIdTF.getText().trim().isEmpty() || assetNameTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all text fields!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id = assetIdTF.getText().trim();
        String name = assetNameTF.getText().trim();
        String type = assetTypeCB.getSelectedItem().toString(); 
        String location = locationCB.getSelectedItem().toString(); 
        String status = statusCB.getSelectedItem().toString(); 

        HospitalAsset updatedAsset = new HospitalAsset(id, name, type, location, status);

        AdminStaff admin = new AdminStaff();
        boolean success = admin.updateAsset(updatedAsset);

        if (success) {
            JOptionPane.showMessageDialog(this, "Asset Updated Successfully!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update asset.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        assetIdTF.setText("");
        assetNameTF.setText("");
        assetTypeCB.setSelectedIndex(0);
        locationCB.setSelectedIndex(0);
        statusCB.setSelectedIndex(0);
        
        refreshTable();
    }//GEN-LAST:event_updateAssetBTActionPerformed

    private void deleteAssetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAssetBTActionPerformed
        // TODO add your handling code here:
        int selectedRow = assetsTB.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an asset from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String assetId = assetsTB.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this asset (ID: " + assetId + ")?", 
                "Confirm Deletion", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {

            AdminStaff admin = new AdminStaff();
            boolean success = admin.deleteAsset(assetId);

            if (success) {
                JOptionPane.showMessageDialog(this, "Asset Deleted Successfully!");



            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete asset.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        assetIdTF.setText("");
        assetNameTF.setText("");
        assetTypeCB.setSelectedIndex(0);
        locationCB.setSelectedIndex(0);
        statusCB.setSelectedIndex(0);
        refreshTable();
    }//GEN-LAST:event_deleteAssetBTActionPerformed

    private void assetsTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assetsTBMouseClicked
        // TODO add your handling code here:
        int selectedRow = assetsTB.getSelectedRow();

        if (selectedRow != -1) {

            String id = assetsTB.getValueAt(selectedRow, 0).toString();
            String name = assetsTB.getValueAt(selectedRow, 1).toString();
            String type = assetsTB.getValueAt(selectedRow, 2).toString();
            String location = assetsTB.getValueAt(selectedRow, 3).toString();
            String status = assetsTB.getValueAt(selectedRow, 4).toString();

            assetIdTF.setText(id);
            assetNameTF.setText(name);

            assetTypeCB.setSelectedItem(type);
            locationCB.setSelectedItem(location);
            statusCB.setSelectedItem(status);
        }
    }//GEN-LAST:event_assetsTBMouseClicked
    
    public void refreshTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) assetsTB.getModel();
        model.setRowCount(0); 
        java.util.ArrayList<String[]> assetsData = TableManager.getAssets();
        for (int i = 0; i < assetsData.size(); i++) {
        String[] row = assetsData.get(i);
        model.addRow(row);
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Asset_Management().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAssetBT;
    private javax.swing.JTextField assetIdTF;
    private javax.swing.JTextField assetNameTF;
    private javax.swing.JComboBox<String> assetTypeCB;
    private javax.swing.JTable assetsTB;
    private javax.swing.JButton backBT;
    private javax.swing.JButton deleteAssetBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> locationCB;
    private javax.swing.JButton logoutBT;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JButton updateAssetBT;
    // End of variables declaration//GEN-END:variables
}
