/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.AdminStaff;
import hospitalmanagementsystem.model.TableManager;

/**
 *
 * @author tbash
 */
public class Assign_Managers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Assign_Managers.class.getName());

    /**
     * Creates new form Assign_Managers
     */
    public Assign_Managers() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsTB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        doctorIdTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doctorNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        managerTF = new javax.swing.JTextField();
        assignBT = new javax.swing.JButton();
        updateBT = new javax.swing.JButton();
        removeBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        backBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        filterCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doctorsTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor ID", "Doctor Name", "Assigned Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorsTB.setMinimumSize(new java.awt.Dimension(300, 80));
        doctorsTB.getTableHeader().setReorderingAllowed(false);
        doctorsTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorsTB);

        jLabel1.setText("Doctor ID");

        jLabel2.setText("Doctor Name");

        jLabel3.setText("Manager");

        assignBT.setText("Assign Manager");
        assignBT.addActionListener(this::assignBTActionPerformed);

        updateBT.setText("Update Assign");
        updateBT.addActionListener(this::updateBTActionPerformed);

        removeBT.setText("Remove Assign ");
        removeBT.addActionListener(this::removeBTActionPerformed);

        logoutBT.setBackground(new java.awt.Color(0, 51, 153));
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        backBT.setText("Back");
        backBT.addActionListener(this::backBTActionPerformed);

        jLabel4.setText("Assign Manager");

        filterCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Unassigned" }));
        filterCB.addActionListener(this::filterCBActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(assignBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(removeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(doctorIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(doctorNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(managerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBT)
                    .addComponent(backBT))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(managerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBT)
                    .addComponent(removeBT)
                    .addComponent(updateBT))
                .addGap(22, 22, 22)
                .addComponent(filterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new AdminStaff_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void assignBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBTActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorsTB.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a doctor from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        if (managerTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a valid manager from the list!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }


        String doctorId = doctorsTB.getValueAt(selectedRow, 0).toString();
        String managerName = managerTF.getText().toString();
        AdminStaff admin = new AdminStaff();
        
        if (!admin.checkManager(managerName)) {
        JOptionPane.showMessageDialog(this, "Manager name not found in the system! Please check the spelling.", "Error",JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        boolean success = admin.assignManager(doctorId, managerName);

        if (success) {
            JOptionPane.showMessageDialog(this, "Manager Assigned Successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to assign manager.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        doctorIdTF.setText("");
        doctorNameTF.setText("");
        managerTF.setText("");
        
        refreshTable();
        
    }//GEN-LAST:event_assignBTActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorsTB.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a doctor from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        if (managerTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a valid manager from the list!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }


        String doctorId = doctorsTB.getValueAt(selectedRow, 0).toString();
        String managerName = managerTF.getText().toString();
        AdminStaff admin = new AdminStaff();
        
        if (!admin.checkManager(managerName)) {
        JOptionPane.showMessageDialog(this, "Manager name not found in the system! Please check the spelling.", "Error",JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        boolean success = admin.assignManager(doctorId, managerName);

        if (success) {
            JOptionPane.showMessageDialog(this, "Manager Assigned Successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to assign manager.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        doctorIdTF.setText("");
        doctorNameTF.setText("");
        managerTF.setText("");
        
        refreshTable();
    }//GEN-LAST:event_updateBTActionPerformed

    private void removeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTActionPerformed
        int selectedRow = doctorsTB.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a doctor from the table first!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String doctorId = doctorsTB.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to remove the manager from this doctor?", 
            "Confirm Removal", 
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {

            AdminStaff admin = new AdminStaff();
            boolean success = admin.assignManager(doctorId, "Unassigned");

            if (success) {
                JOptionPane.showMessageDialog(this, "Manager Removed Successfully!");

                managerTF.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to remove manager.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            refreshTable();
        }
        
        doctorIdTF.setText("");
        doctorNameTF.setText("");
        managerTF.setText("");
        
        
        refreshTable();
    }//GEN-LAST:event_removeBTActionPerformed

    private void doctorsTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsTBMouseClicked
        // TODO add your handling code here:
        int selectedRow = doctorsTB.getSelectedRow();

        if (selectedRow != -1) {
        
        String doctorId = doctorsTB.getValueAt(selectedRow, 0).toString();
        String doctorName = doctorsTB.getValueAt(selectedRow, 1).toString();
        String currentManager = doctorsTB.getValueAt(selectedRow, 2).toString();
        
        doctorIdTF.setText(doctorId);
        doctorNameTF.setText(doctorName);
        
        if (currentManager.equals("Unassigned_Manager")) {
            managerTF.setText("");
        } else {
            managerTF.setText(currentManager);
        }
}
    }//GEN-LAST:event_doctorsTBMouseClicked

    private void filterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterCBActionPerformed
        // TODO add your handling code here:
        String selectedFilter = filterCB.getSelectedItem().toString();

        DefaultTableModel model = (javax.swing.table.DefaultTableModel) doctorsTB.getModel();

        TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new TableRowSorter<>(model);
        doctorsTB.setRowSorter(sorter);

        if (selectedFilter.equals("All")) {
            sorter.setRowFilter(null); 
        } else if (selectedFilter.equals("Unassigned")) {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("^Unassigned$", 2));
        }
    }//GEN-LAST:event_filterCBActionPerformed
    
    public void refreshTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) doctorsTB.getModel();
        model.setRowCount(0); 
    
        ArrayList<String[]> doctorsData = TableManager.getDoctorsAndManagers();
    
        for (int i = 0; i < doctorsData.size(); i++) {
            String[] row = doctorsData.get(i);
            model.addRow(row);
        }
    
}  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Assign_Managers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBT;
    private javax.swing.JButton backBT;
    private javax.swing.JTextField doctorIdTF;
    private javax.swing.JTextField doctorNameTF;
    private javax.swing.JTable doctorsTB;
    private javax.swing.JComboBox<String> filterCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBT;
    private javax.swing.JTextField managerTF;
    private javax.swing.JButton removeBT;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables
}
