/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem.doctor;


/**
 *
 * @author shanshan
 */
public class DoctorDashboardGUI extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(DoctorDashboardGUI.class.getName());



    public DoctorDashboardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editprofileBtn = new javax.swing.JButton();
        vitalsignsBtn = new javax.swing.JButton();
        consultationBtn = new javax.swing.JButton();
        prescriptionBtn = new javax.swing.JButton();
        diagnosticrequestBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hospital Mangement System");

        jLabel2.setText("Doctor DashBoard");

        editprofileBtn.setText("Edit Personal Profile ");
        editprofileBtn.addActionListener(this::editprofileBtnActionPerformed);

        vitalsignsBtn.setText("Log Patient Vital Signs");
        vitalsignsBtn.addActionListener(this::vitalsignsBtnActionPerformed);

        consultationBtn.setText("Write Consultation Notes");
        consultationBtn.addActionListener(this::consultationBtnActionPerformed);

        prescriptionBtn.setText("Issue Prescription");
        prescriptionBtn.addActionListener(this::prescriptionBtnActionPerformed);

        diagnosticrequestBtn.setText("Request Lab / X-Ray / Imaging");
        diagnosticrequestBtn.addActionListener(this::diagnosticrequestBtnActionPerformed);

        logoutBtn.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(consultationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(diagnosticrequestBtn))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prescriptionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vitalsignsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editprofileBtn)
                    .addComponent(vitalsignsBtn))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationBtn)
                    .addComponent(prescriptionBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosticrequestBtn)
                    .addComponent(logoutBtn))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vitalsignsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsignsBtnActionPerformed
        // TODO add your handling code here:'
        
    VitalSignsGUI vs = new VitalSignsGUI();
    vs.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_vitalsignsBtnActionPerformed

    private void consultationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationBtnActionPerformed
        // TODO add your handling code here:
    ConsultationGUI cg = new ConsultationGUI();
    cg.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_consultationBtnActionPerformed

    private void prescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionBtnActionPerformed
        // TODO add your handling code here:
        PrescriptionGUI pg = new PrescriptionGUI();
    pg.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_prescriptionBtnActionPerformed

    private void diagnosticrequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticrequestBtnActionPerformed

        DiagnosticRequestGUI dr = new DiagnosticRequestGUI();
    dr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_diagnosticrequestBtnActionPerformed

    private void editprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileBtnActionPerformed
    EditProfileGUI ep = new EditProfileGUI();
    ep.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_editprofileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DoctorDashboardGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultationBtn;
    private javax.swing.JButton diagnosticrequestBtn;
    private javax.swing.JButton editprofileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton prescriptionBtn;
    private javax.swing.JButton vitalsignsBtn;
    // End of variables declaration//GEN-END:variables
}
