/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.AdminStaff;
import hospitalmanagementsystem.model.TableManager;

/**
 *
 * @author tbash
 */
public class System_Configuration_Rate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(System_Configuration_Rate.class.getName());

    /**
     * Creates new form System_Configuration
     */
    public System_Configuration_Rate() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        rateTF = new javax.swing.JTextField();
        consultationTypeCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ratesTB = new javax.swing.JTable();
        updateBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        backBT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Page2BT = new javax.swing.JButton();
        page1BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Rate");

        consultationTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Consultation", "General Consultation", "Specialist Consultation", "Follow-up Consultation", "Emergency Consultation" }));

        jLabel2.setText("Consultation Type");

        ratesTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Consultation", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ratesTB.getTableHeader().setReorderingAllowed(false);
        ratesTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratesTBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ratesTB);

        updateBT.setText("Update");
        updateBT.addActionListener(this::updateBTActionPerformed);

        logoutBT.setBackground(new java.awt.Color(0, 51, 153));
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        backBT.setText("Back");
        backBT.addActionListener(this::backBTActionPerformed);

        jLabel6.setText(" SYSTEM CONFIGURATION - CONSULTATION RATE");

        Page2BT.setText("2");
        Page2BT.addActionListener(this::Page2BTActionPerformed);

        page1BT.setBackground(new java.awt.Color(51, 51, 51));
        page1BT.setText("1");
        page1BT.addActionListener(this::page1BTActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addGap(102, 102, 102))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(consultationTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(page1BT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Page2BT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutBT)
                            .addComponent(backBT)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Page2BT)
                            .addComponent(page1BT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateBT)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratesTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratesTBMouseClicked
        // TODO add your handling code here:
        int selectedRow = ratesTB.getSelectedRow();
        if (selectedRow != -1) {
        String type = ratesTB.getValueAt(selectedRow, 0).toString();
        String rate = ratesTB.getValueAt(selectedRow, 1).toString();
    
        consultationTypeCB.setSelectedItem(type); 
        rateTF.setText(rate);                    
        }
    }//GEN-LAST:event_ratesTBMouseClicked

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        String selectedType = consultationTypeCB.getSelectedItem().toString();

        if (selectedType.equals("Select Consultation")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid Consultation Type from the list!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (rateTF.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid rate!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String rate = rateTF.getText().trim();
        AdminStaff admin = new AdminStaff();
        boolean success = admin.updatePrice(selectedType, rate);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Consultation Rate Updated Successfully!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update rate.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        rateTF.setText("");
        consultationTypeCB.setSelectedIndex(0);
        refreshTable(); 
    }//GEN-LAST:event_updateBTActionPerformed

    private void page1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1BTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_page1BTActionPerformed

    private void Page2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Page2BTActionPerformed
        // TODO add your handling code here:
        new System_Configuration_Insurance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Page2BTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new AdminStaff_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTActionPerformed
    
    public void refreshTable() {
    DefaultTableModel model = (javax.swing.table.DefaultTableModel) ratesTB.getModel(); 
    model.setRowCount(0); 
    ArrayList<String[]> data = TableManager.getPrices();
    
    for (int i = 0; i < data.size(); i++) {
        model.addRow(data.get(i));
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new System_Configuration_Rate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Page2BT;
    private javax.swing.JButton backBT;
    private javax.swing.JComboBox<String> consultationTypeCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton page1BT;
    private javax.swing.JTextField rateTF;
    private javax.swing.JTable ratesTB;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables
}
