/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.AdminStaff;
import hospitalmanagementsystem.model.Insurance;
import hospitalmanagementsystem.model.TableManager;

/**
 *
 * @author tbash
 */
public class System_Configuration_Insurance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(System_Configuration_Insurance.class.getName());

    /**
     * Creates new form System_Configuration_Insurance
     */
    public System_Configuration_Insurance() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBT = new javax.swing.JButton();
        updateBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        insuranceIdTF = new javax.swing.JTextField();
        insuranceNameTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        insurancesTB = new javax.swing.JTable();
        statusCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        page2BT = new javax.swing.JButton();
        page1BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SYSTEM CONFIGURATION - ACCEPTED INSURANCE NETWORKS");

        addBT.setText("Add Insurance");
        addBT.addActionListener(this::addBTActionPerformed);

        updateBT.setText("Update");
        updateBT.addActionListener(this::updateBTActionPerformed);

        deleteBT.setText("Delete");
        deleteBT.addActionListener(this::deleteBTActionPerformed);

        insurancesTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        insurancesTB.getTableHeader().setReorderingAllowed(false);
        insurancesTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insurancesTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(insurancesTB);

        statusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", "Under Review" }));

        jLabel2.setText("Insurance ID");

        jLabel3.setText("Insurance Name");

        jLabel4.setText("Insurance Status");

        page2BT.setBackground(new java.awt.Color(51, 51, 51));
        page2BT.setText("2");
        page2BT.addActionListener(this::page2BTActionPerformed);

        page1BT.setText("1");
        page1BT.addActionListener(this::page1BTActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(insuranceIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insuranceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(page1BT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(page2BT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(page2BT)
                    .addComponent(page1BT))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBT)
                    .addComponent(updateBT)
                    .addComponent(addBT))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void page2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page2BTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_page2BTActionPerformed

    private void page1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1BTActionPerformed
        // TODO add your handling code here:
        new System_Configuration_Rate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_page1BTActionPerformed

    private void insurancesTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insurancesTBMouseClicked
        // TODO add your handling code here:
        int row = insurancesTB.getSelectedRow();
        if (row != -1) {
            insuranceIdTF.setText(insurancesTB.getValueAt(row, 0).toString());
            insuranceNameTF.setText(insurancesTB.getValueAt(row, 1).toString());
            statusCB.setSelectedItem(insurancesTB.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_insurancesTBMouseClicked

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        String id = insuranceIdTF.getText().trim();
        String name = insuranceNameTF.getText().trim();
        String status = statusCB.getSelectedItem().toString();

        if (id.isEmpty() || name.isEmpty() || status.equals("Status")) { 
            JOptionPane.showMessageDialog(this, "Please fill all fields and select a valid status!");
            return;
        }

        AdminStaff admin = new AdminStaff();
        if (admin.checkInsurance(id)) {
            JOptionPane.showMessageDialog(this, "ID already exists!");
            return;
        }

        Insurance ins = new Insurance(id, name, status);
        if (admin.addInsurance(ins)) {
            JOptionPane.showMessageDialog(this, "Added Successfully!");
            refreshTable();
        }
        
        insuranceIdTF.setText("");
        insuranceNameTF.setText("");
        statusCB.setSelectedIndex(0);
        refreshTable();
    }//GEN-LAST:event_addBTActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        int row = insurancesTB.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select an insurance from the table first!");
            return;
        }

        String id = insuranceIdTF.getText().trim();
        String name = insuranceNameTF.getText().trim();
        String status = statusCB.getSelectedItem().toString();

        Insurance ins = new Insurance(id, name, status);
        AdminStaff admin = new AdminStaff();

        if (admin.updateInsurance(ins)) {
            JOptionPane.showMessageDialog(this, "Updated Successfully!");
        }
        
        insuranceIdTF.setText("");
        insuranceNameTF.setText("");
        statusCB.setSelectedIndex(0);
        refreshTable();

    }//GEN-LAST:event_updateBTActionPerformed

    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
        int row = insurancesTB.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select an insurance from the table first!");
            return;
        }

        String id = insurancesTB.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Delete this insurance?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            AdminStaff admin = new AdminStaff();
            if (admin.deleteInsurance(id)) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
            }
        }
        
        insuranceIdTF.setText("");
        insuranceNameTF.setText("");
        statusCB.setSelectedIndex(0);
        refreshTable();

        
    }//GEN-LAST:event_deleteBTActionPerformed
    
    public void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) insurancesTB.getModel();
    model.setRowCount(0); 
    ArrayList<String[]> data = TableManager.getInsurances();
    for (int i = 0; i < data.size(); i++) {
        model.addRow(data.get(i));
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new System_Configuration_Insurance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton deleteBT;
    private javax.swing.JTextField insuranceIdTF;
    private javax.swing.JTextField insuranceNameTF;
    private javax.swing.JTable insurancesTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton page1BT;
    private javax.swing.JButton page2BT;
    private javax.swing.JComboBox<String> statusCB;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables
}
