/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;

import models.AdminStaff;
import hospitalmanagementsystem.model.TableManager;

/**
 *
 * @author tbash
 */
public class User_Management extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_Management.class.getName());

    /**
     * Creates new form User_Management
     */
    public User_Management() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        useridTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        roleCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        passwordPF = new javax.swing.JPasswordField();
        addBT = new javax.swing.JButton();
        updateBT = new javax.swing.JButton();
        deletBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        backBT = new javax.swing.JButton();
        filterCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usersTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Password", "Phone Number", "Email", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTB.getTableHeader().setReorderingAllowed(false);
        usersTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTB);

        jLabel1.setText("Name");

        jLabel2.setText("User ID");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Role");

        jLabel5.setText("password");

        nameTF.addActionListener(this::nameTFActionPerformed);

        useridTF.addActionListener(this::useridTFActionPerformed);

        phoneTF.addActionListener(this::phoneTFActionPerformed);

        roleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin Staff", "Medical Manager", "Doctor", "Patient" }));
        roleCB.setToolTipText("");
        roleCB.addActionListener(this::roleCBActionPerformed);

        jLabel6.setText("Email");

        emailTF.addActionListener(this::emailTFActionPerformed);

        addBT.setBackground(new java.awt.Color(0, 8, 142));
        addBT.setText("Add");
        addBT.addActionListener(this::addBTActionPerformed);

        updateBT.setBackground(new java.awt.Color(24, 128, 10));
        updateBT.setText("Update");
        updateBT.addActionListener(this::updateBTActionPerformed);

        deletBT.setBackground(new java.awt.Color(151, 0, 0));
        deletBT.setText("Delete");
        deletBT.addActionListener(this::deletBTActionPerformed);

        logoutBT.setBackground(new java.awt.Color(0, 51, 153));
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        backBT.setText("Back");
        backBT.addActionListener(this::backBTActionPerformed);

        filterCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin Staff", "Medical Manager", "Doctor", "Patient" }));
        filterCB.addActionListener(this::filterCBActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(deletBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(useridTF)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordPF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneTF)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBT)
                    .addComponent(backBT))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBT)
                    .addComponent(updateBT)
                    .addComponent(deletBT))
                .addGap(18, 18, 18)
                .addComponent(filterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void roleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleCBActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new AdminStaff_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void useridTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridTFActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        
        if (roleCB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid role from the list!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String id = useridTF.getText(); 
        String name = nameTF.getText();
        String pass = passwordPF.getText();
        String role = roleCB.getSelectedItem().toString(); 
        String email = emailTF.getText();
        String phone = phoneTF.getText();

    AdminStaff admin = new AdminStaff();
    boolean success = admin.updateUser(id, name, pass, role, email, phone);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "User Updated Successfully!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update user.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
       useridTF.setText("");
       nameTF.setText("");
       passwordPF.setText("");
       roleCB.setSelectedItem("Select role");
       emailTF.setText("");
       phoneTF.setText("");
       refreshTable();
    }//GEN-LAST:event_updateBTActionPerformed

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTFActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        
        if (roleCB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid role from the list!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String id = useridTF.getText(); 
        String name = nameTF.getText();
        String pass = passwordPF.getText();
        String role = roleCB.getSelectedItem().toString(); 
        String email = emailTF.getText();
        String phone = phoneTF.getText();
        
        
        
        AdminStaff admin = new AdminStaff();
        boolean success = admin.createUser(id, name, pass, role, email, phone);
        
        if (success) {
                JOptionPane.showMessageDialog(this, "User Add Successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Error adding User!");
            }
        
       useridTF.setText("");
       nameTF.setText("");
       passwordPF.setText("");
       roleCB.setSelectedItem("Select role");
       emailTF.setText("");
       phoneTF.setText("");
       refreshTable();
    }//GEN-LAST:event_addBTActionPerformed

    private void deletBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletBTActionPerformed
        // TODO add your handling code here:
        
        if (roleCB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid role from the list!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String targetId = useridTF.getText(); 
        String role = roleCB.getSelectedItem().toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            AdminStaff admin = new AdminStaff();
            boolean success = admin.deleteUser(targetId, role);

            if (success) {
                JOptionPane.showMessageDialog(this, "User Deleted Successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Error Deleting User!");
            }
        }
        
       useridTF.setText("");
       nameTF.setText("");
       passwordPF.setText("");
       roleCB.setSelectedItem("Select role");
       emailTF.setText("");
       phoneTF.setText("");
       refreshTable();
    }//GEN-LAST:event_deletBTActionPerformed

    private void usersTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTBMouseClicked
        // TODO add your handling code here:
        int selectedRow = usersTB.getSelectedRow();

        if (selectedRow != -1) {
            javax.swing.table.DefaultTableModel model = (DefaultTableModel) usersTB.getModel();
            useridTF.setText(model.getValueAt(selectedRow, 0).toString());
            nameTF.setText(model.getValueAt(selectedRow, 1).toString());
            passwordPF.setText(model.getValueAt(selectedRow, 2).toString());
            roleCB.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
            emailTF.setText(model.getValueAt(selectedRow, 4).toString());
            phoneTF.setText(model.getValueAt(selectedRow, 3).toString());
            }
    }//GEN-LAST:event_usersTBMouseClicked

    private void filterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterCBActionPerformed
        // TODO add your handling code here:
        String selectedRole = filterCB.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) usersTB.getModel();

        TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        usersTB.setRowSorter(sorter);

        if (selectedRole.equals("All")) {
            sorter.setRowFilter(null); 
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("^" + selectedRole + "$", 5));
        }
    }//GEN-LAST:event_filterCBActionPerformed
    
public void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) usersTB.getModel();
    model.setRowCount(0); 
    
    ArrayList<String[]> usersData = TableManager.getAllUsers();
    for (int i = 0; i < usersData.size(); i++) {
        String[] row = usersData.get(i);
        model.addRow(row);
    }
    
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_Management().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton backBT;
    private javax.swing.JButton deletBT;
    private javax.swing.JTextField emailTF;
    private javax.swing.JComboBox<String> filterCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBT;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JComboBox<String> roleCB;
    private javax.swing.JButton updateBT;
    private javax.swing.JTextField useridTF;
    private javax.swing.JTable usersTB;
    // End of variables declaration//GEN-END:variables
}
