/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem.doctor;
import hospitalmanagementsystem.doctor.DoctorDashboardGUI;
import javax.swing.JOptionPane;
import java.io.*;
/**
 *
 * @author shanshan
 */
public class VitalSignsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VitalSignsGUI.class.getName());

    /**
     * Creates new form VitalSignsFrame
     */
    public VitalSignsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        patientIdTf = new javax.swing.JTextField();
        temperatureTf = new javax.swing.JTextField();
        heartrateTf = new javax.swing.JTextField();
        bloodpressureTf = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("  LOG PATIENT VITAL SIGNS");

        jLabel2.setText("Patient ID:");

        jLabel3.setText("Temperature:");

        jLabel4.setText("Heart Rate:  ");

        jLabel5.setText("Blood Pressure: ");

        saveBtn.setText("Save ");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        backBtn.setText("Back ");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(temperatureTf, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(heartrateTf)
                            .addComponent(patientIdTf)
                            .addComponent(bloodpressureTf, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(saveBtn)
                        .addGap(88, 88, 88)
                        .addComponent(backBtn)))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addComponent(patientIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(temperatureTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(heartrateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bloodpressureTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(backBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
    DoctorDashboardGUI db = new DoctorDashboardGUI();
    db.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed
public boolean patientExists(String patientId) {

    try {

        FileReader fr = new FileReader("medical_records.txt");
        BufferedReader br = new BufferedReader(fr);

        String line = null;

        while ((line = br.readLine()) != null) {

            String value[] = line.split("\\|");

            if (value[0].equalsIgnoreCase(patientId)) {

                br.close();
                fr.close();

                return true;
            }
        }

        br.close();
        fr.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error reading patient file"
        );
    }

    return false;
}
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
String patientId = patientIdTf.getText();
    String temperature = temperatureTf.getText();
    String heartRate = heartrateTf.getText();
    String bloodPressure = bloodpressureTf.getText();

    // Check empty fields
    if (patientId.isEmpty()
            || temperature.isEmpty()
            || heartRate.isEmpty()
            || bloodPressure.isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Please fill in all fields"
        );

    } else {

        // Check Patient ID
        if (patientExists(patientId) == false) {

            JOptionPane.showMessageDialog(
                    null,
                    "Patient ID not found"
            );

        } else {

        try {

    // Temperature must be a number
    double temperatureValue =
            Double.parseDouble(temperature);

    // Heart Rate must be a whole number
    int heartRateValue =
            Integer.parseInt(heartRate);

    // Blood Pressure must contain /
    String bloodPressureValue[] =
            bloodPressure.split("/");

    if (bloodPressureValue.length != 2) {

        JOptionPane.showMessageDialog(
                null,
                "Blood Pressure must be entered correctly"
        );

    } else {

        // Both blood pressure values must be numbers
        int systolic =
                Integer.parseInt(bloodPressureValue[0]);

        int diastolic =
                Integer.parseInt(bloodPressureValue[1]);

        // Check all values are greater than 0
        if (temperatureValue <= 0
                || heartRateValue <= 0
                || systolic <= 0
                || diastolic <= 0) {

            JOptionPane.showMessageDialog(
                    null,
                    "Vital sign values must be greater than 0"
            );

        } else {

            // SAVE CODE GOES HERE

        }
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            null,
            "Please enter valid numbers for Temperature, Heart Rate and Blood Pressure"
    );
}
        }
    }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VitalSignsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodpressureTf;
    private javax.swing.JTextField heartrateTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField patientIdTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField temperatureTf;
    // End of variables declaration//GEN-END:variables
}
